spring:
  # Freemarker
  freemarker:
    charset: UTF-8
    enabled: true
    prefer-file-system-access: false
    settings:
      auto_import: '"/spring.ftl" as spring, "/layout.ftl" as layout'
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd
      default_encoding: UTF-8
      locale: zh_CN
      number_format: '#.##'
      template_update_delay: 0
    template-loader-path: classpath:templates/
  
  # spring cloud stream rabbitmq
  cloud:
    stream:
      binders:
        rabbitmq1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: centos7-master
                port: 5672
                username: walter
                password: 123456
                virtual-host: /
      bindings:
        refreshStaticMemoryDataInput:
          destination: REFRESH_STATIC_MEMORY_DATA
          binder: rabbitmq1
          #group: demo-webapp
        refreshStaticMemoryDataOutput:
          destination: REFRESH_STATIC_MEMORY_DATA
          binder: rabbitmq1
        refreshRoleResourceInput:
          destination: REFRESH_ROLE_RESOURCE
          binder: rabbitmq1
          #group: demo-webapp
        refreshRoleResourceOutout:
          destination: REFRESH_ROLE_RESOURCE
          binder: rabbitmq1