# 自定义系统属性
custom:
    security:
        httpBasic:
            enable: false
# Eureka
eureka:
    client:
        fetch-registry: true
        register-with-eureka: false
        service-url:
            defaultZone: http://localhost:7001/eureka/
# Feign
feign:
    client:
        config:
            default:
                connect-timeout: 10000
                read-timeout: 10000
# Actuator
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 7080
    servlet:
        context-path: /lychee
spring:
    # DataSource
    datasource:
        password: ''
        url: jdbc:mysql://localhost/lychee?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: root
    # Freemarker
    freemarker:
        charset: UTF-8
        enabled: true
        prefer-file-system-access: false
        settings:
            auto_import: '"/spring.ftl" as spring, "/layout.ftl" as layout'
            date_format: yyyy-MM-dd
            datetime_format: yyyy-MM-dd
            default_encoding: UTF-8
            locale: zh_CN
            number_format: '#.##'
            template_update_delay: 0
        template-loader-path: classpath:templates/
    # JPA
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        show-sql: true
