# 自定义系统属性
custom:
  security:
    httpBasicEnable: true
    login:
      jwt:
        secret: AUTH-CENTER-JWT-SECRET
        header: Jwt
        alivedMinutes: 60
      captcha:
        alivedSeconds: 300
      rememberMe:
        tokenValiditySeconds: 3600

spring:
  # Redis
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 
    lettuce:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
        max-wait: 10000ms

  # spring cloud stream rabbitmq
  cloud:
    stream:
      binders:
        rabbitmq1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: centos7-master
                port: 5672
                username: walter
                password: 123456
                virtual-host: /
      bindings:
        refreshStaticMemoryDataInput:
          destination: REFRESH_STATIC_MEMORY_DATA
          binder: rabbitmq1
        refreshStaticMemoryDataOutput:
          destination: REFRESH_STATIC_MEMORY_DATA
          binder: rabbitmq1
        refreshRoleResourceInput:
          destination: REFRESH_ROLE_RESOURCE
          binder: rabbitmq1
          #group: demo-webapp
        refreshRoleResourceOutput:
          destination: REFRESH_ROLE_RESOURCE
          binder: rabbitmq1
        refreshRoleInput:
          destination: REFRESH_ROLE
          binder: rabbitmq1
        refreshRoleOutput:
          destination: REFRESH_ROLE
          binder: rabbitmq1