# Eureka
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:7110/eureka/
# Feign
feign:
    client:
        config:
            default:
                connect-timeout: 4000
                read-timeout: 4000
    # Feign hystrix
    hystrix:
        enabled: true

# Hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

# Actuator
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 7120
spring:
    application:
        name: zuul
    # DataSource
    datasource:
        password: ''
        url: jdbc:mysql://localhost/lychee?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: root
    # JPA
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        show-sql: true
    # Zipkin
    zipkin:
        base-url: http://localhost:9411/
    # Sleuth
    sleuth:
        sampler:
            probability: 1
# Zuul
zuul:
  # 取消Zuul的默认路由规则
  ignored-patterns:
  - /res/**
  - /user/**
  routes:
    res: /gateway/res/**
    user: /gateway/user/**
  # 默认情况下，敏感请求头"Cookie", "Set-Cookie", "Authorization"是不会带到微服务中的，因此要至空使其可以带过去
  sensitive-headers: 
